plugin 'cocoapods-art', :sources => [
  'cocoapods-cocoapods',
  'NFMC.cocoapods.Release'
]

use_frameworks!

platform :ios, '9.0'

target 'MarvelCore_Example' do
  pod 'MarvelCore', :path => '../'

end
